#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.32.0 (build#409)
// Adapted for nrf24_sniffer — nRF24L01+ promiscuous sniffer on CC1352P7
// Device: CC1352P7 Rev. A (1.0)
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>

// TI-RTOS RF Mode Object
extern RF_Mode RF_prop;

// RF Core API Commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_PA_t RF_nrf24_cmdPropRadioDivSetup_1M;
extern rfc_CMD_FS_t                      RF_cmdFs;
extern rfc_CMD_PROP_RX_ADV_t             RF_nrf24_cmdPropRxAdv;
extern rfc_CMD_PROP_TX_t                 RF_nrf24_cmdPropTx;

// RF Core API Overrides
extern uint32_t pOverrides[];

/**
 * RF_nrf24_update_channel() — Cambia el canal RF en RAM.
 * Llamar antes de re-ejecutar CMD_PROP_RADIO_DIV_SETUP si se cambia de canal.
 *
 * @param channel  Canal nRF24 (0–125). Frecuencia = 2400 + channel MHz.
 */
static inline void RF_nrf24_update_channel(uint8_t channel)
{
    if (channel > 125) { channel = 125; }
    RF_nrf24_cmdPropRadioDivSetup_1M.centerFreq = (uint16_t)(2400u + channel);
}

#endif // _SMARTRF_SETTINGS_H_
