//*********************************************************************************
// Generated by SmartRF Studio version 2.32.0 (build#409)
// Adapted for nrf24_sniffer — nRF24L01+ promiscuous sniffer on CC1352P7
// Device: CC1352P7 Rev. A (1.0)
//
// Parameter summary:
// Frequency:    2476.00000 MHz  (channel 76, default nRF24)
// Symbol Rate:  1000.00000 kBaud
// Deviation:    160.000 kHz
// RX Filter BW: 1567.2 kHz
// Sync Word:    0xAAAAAAAA (32 bits, preamble trick)
// Preamble:     4 Bytes
// Packet Len:   Fixed 37 bytes (max ESB frame)
// CRC:          Disabled (parsed in software)
// Whitening:    No whitening
// TX Power:     0 dBm
//*********************************************************************************

#include "smartrf_settings.h"

#include DeviceFamily_constructPath(rf_patches/rf_patch_cpe_prop.h)

// TI-RTOS RF Mode Object
RF_Mode RF_prop =
{
    .rfMode = RF_MODE_AUTO,
    .cpePatchFxn = &rf_patch_cpe_prop,
    .mcePatchFxn = 0,
    .rfePatchFxn = 0
};


// Overrides for CMD_PROP_RADIO_DIV_SETUP_PA
uint32_t pOverrides[] =
{
    // override_tc706.xml
    // Tx: Configure PA ramp time, PACTL2.RC=0x3 (in ADI0, set PACTL2[4:3]=0x3)
    ADI_2HALFREG_OVERRIDE(0,16,0x8,0x8,17,0x1,0x1),
    // Rx: Set AGC reference level to 0x1A (default: 0x2E)
    HW_REG_OVERRIDE(0x609C,0x001A),
    // Rx: Set RSSI offset to adjust reported RSSI by -1 dB (default: -2), trimmed for external bias and differential configuration
    (uint32_t)0x000188A3,
    // Rx: Set anti-aliasing filter bandwidth to 0xD (in ADI0, set IFAMPCTL3[7:4]=0xD)
    ADI_HALFREG_OVERRIDE(0,61,0xF,0xD),
    // override_prop_common_sub1g.xml
    // TX: Set FSCA divider bias to 1
    HW32_ARRAY_OVERRIDE(0x405C,0x0001),
    // TX: Set FSCA divider bias to 1
    (uint32_t)0x08141131,
    // override_prop_common.xml
    // DC/DC regulator: In Tx with 14 dBm PA setting, use DCDCCTL5[3:0]=0xF (DITHER_EN=1 and IPEAK=7). In Rx, use default settings.
    (uint32_t)0x00F788D3,
    (uint32_t)0xFFFFFFFF
};


// CMD_PROP_RADIO_DIV_SETUP_PA — 1 Mbps 2-GFSK, 2476 MHz (canal 76, default nRF24)
rfc_CMD_PROP_RADIO_DIV_SETUP_PA_t RF_nrf24_cmdPropRadioDivSetup_1M =
{
    .commandNo = 0x3807,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .modulation.modType = 0x1,
    .modulation.deviation = 0x280,
    .modulation.deviationStepSz = 0x0,
    .symbolRate.preScale = 0xF,
    .symbolRate.rateWord = 0xA0000,        /* 1 Mbps — SmartRF Studio verified */
    .symbolRate.decimMode = 0x0,
    .rxBw = 0x62,                          /* ≈ 1567 kHz BW */
    .preamConf.nPreamBytes = 0x4,
    .preamConf.preamMode = 0x0,
    .formatConf.nSwBits = 0x20,
    .formatConf.bBitReversal = 0x0,
    .formatConf.bMsbFirst = 0x1,
    .formatConf.fecMode = 0x0,
    .formatConf.whitenMode = 0x0,
    .config.frontEndMode = 0x0,
    .config.biasMode = 0x1,
    .config.analogCfgMode = 0x0,
    .config.bNoFsPowerUp = 0x0,
    .config.bSynthNarrowBand = 0x0,
    .txPower = 0x2C5D,                     /* 0 dBm */
    .pRegOverride = pOverrides,
    .centerFreq = 0x09AC,                  /* 2476 MHz = canal 76 (0x09AC = 2476) */
    .intFreq = 0x8000,
    .loDivider = 0x00,                     /* 2.4 GHz directo, sin divisor */
    .pRegOverrideTxStd = 0,
    .pRegOverrideTx20 = 0
};


// CMD_FS
// Frequency Synthesizer Programming Command
rfc_CMD_FS_t RF_cmdFs =
{
    .commandNo = 0x0803,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .frequency = 0x09AC,
    .fractFreq = 0x0000,
    .synthConf.bTxMode = 0x0,
    .synthConf.refFreq = 0x0,
    .__dummy0 = 0x00,
    .__dummy1 = 0x00,
    .__dummy2 = 0x00,
    .__dummy3 = 0x0000
};


// CMD_PROP_RX_ADV — Modo promiscuo nRF24 (sync=0xAAAAAAAA, fixed 37 B, sin CRC HW)
rfc_CMD_PROP_RX_ADV_t RF_nrf24_cmdPropRxAdv =
{
    .commandNo = 0x3804,               /* CMD_PROP_RX_ADV */
    .status = 0x0000,
    .pNextOp = 0,
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,   /* TRIG_NOW */
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,             /* COND_ALWAYS */
    .condition.nSkip = 0x0,
    .pktConf.bFsOff = 0x0,
    .pktConf.bRepeatOk = 0x1,          /* continuar en bucle tras RX OK */
    .pktConf.bRepeatNok = 0x1,         /* continuar en bucle tras RX NOK */
    .pktConf.bUseCrc = 0x0,            /* sin CRC HW: parseamos en software */
    .pktConf.bCrcIncSw = 0x0,
    .pktConf.endType = 0x0,
    .pktConf.filterOp = 0x1,           /* en mismatch: recibir y marcar, no parar */
    .rxConf.bIncludeCrc = 0x1,         /* incluir bytes CRC raw en el buffer */
    .maxPktLen = 37,                   /* max ESB: 5B addr + PCF + 32B pld + CRC */
    .hdrConf.numHdrBits = 0x0,         /* sin header de longitud */
    .hdrConf.lenPos = 0,
    .hdrConf.numLenBits = 0,
    .addrConf.addrType = 0x0,          /* sin filtro de dirección HW */
    .addrConf.addrSize = 0x0,
    .addrConf.addrPos = 0x0,
    .addrConf.numAddr = 0x0,
    .syncWord0 = 0xAAAAAAAAUL,         /* preamble trick: captura cualquier nRF24 */
    .syncWord1 = 0x00000000UL,
    .endTime = 0x00000000,
    .endTrigger.triggerType = 0x1,     /* TRIG_NEVER — bloqueante hasta dato */
    .pOutput = 0,                      /* se configura en rx_one_packet() */
    .pQueue = 0,                       /* se configura en rx_one_packet() */
};


// CMD_PROP_TX — Transmisión ESB (inject / replay). Sync word se actualiza en rf_tx_frame().
rfc_CMD_PROP_TX_t RF_nrf24_cmdPropTx =
{
    .commandNo = 0x3801,
    .status = 0x0000,
    .pNextOp = 0, // INSERT APPLICABLE POINTER: (uint8_t*)&xxx
    .startTime = 0x00000000,
    .startTrigger.triggerType = 0x0,
    .startTrigger.bEnaCmd = 0x0,
    .startTrigger.triggerNo = 0x0,
    .startTrigger.pastTrig = 0x0,
    .condition.rule = 0x1,
    .condition.nSkip = 0x0,
    .pktConf.bFsOff = 0x0,
    .pktConf.bUseCrc = 0x0,            /* sin CRC HW: ESB frame ya incluye CRC */
    .pktConf.bVarLen = 0x0,
    .pktLen = 0,                        /* se actualiza antes de cada TX */
    .syncWord = 0xAAAAAAAAUL,          /* se actualiza en rf_tx_frame() */
    .pPkt = 0                          /* se actualiza antes de cada TX */
};

